//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.01.24 at 10:42:10 PM CET 
//


package com.bdzjn.xml.model.act;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="elementName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="elementId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;choice&gt;
 *           &lt;element ref="{http://www.fools.gov.rs/acts}article"/&gt;
 *           &lt;element ref="{http://www.fools.gov.rs/acts}paragraph"/&gt;
 *           &lt;element ref="{http://www.fools.gov.rs/acts}item"/&gt;
 *           &lt;element ref="{http://www.fools.gov.rs/acts}subItem"/&gt;
 *           &lt;element ref="{http://www.fools.gov.rs/acts}ident"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="placement" use="required" type="{http://www.fools.gov.rs/acts}placementType" /&gt;
 *       &lt;attribute name="type" use="required" type="{http://www.fools.gov.rs/acts}amendmentType" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "elementName",
    "elementId",
    "article",
    "paragraph",
    "item",
    "subItem",
    "ident"
})
@XmlRootElement(name = "amendmentItem")
public class AmendmentItem {

    @XmlElement(required = true)
    protected String elementName;
    @XmlElement(required = true)
    protected String elementId;
    protected Article article;
    protected Paragraph paragraph;
    protected Item item;
    protected SubItem subItem;
    protected Ident ident;
    @XmlAttribute(name = "placement", required = true)
    protected PlacementType placement;
    @XmlAttribute(name = "type", required = true)
    protected AmendmentType type;

    /**
     * Gets the value of the elementName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementName() {
        return elementName;
    }

    /**
     * Sets the value of the elementName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementName(String value) {
        this.elementName = value;
    }

    /**
     * Gets the value of the elementId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementId() {
        return elementId;
    }

    /**
     * Sets the value of the elementId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementId(String value) {
        this.elementId = value;
    }

    /**
     * Gets the value of the article property.
     * 
     * @return
     *     possible object is
     *     {@link Article }
     *     
     */
    public Article getArticle() {
        return article;
    }

    /**
     * Sets the value of the article property.
     * 
     * @param value
     *     allowed object is
     *     {@link Article }
     *     
     */
    public void setArticle(Article value) {
        this.article = value;
    }

    /**
     * Gets the value of the paragraph property.
     * 
     * @return
     *     possible object is
     *     {@link Paragraph }
     *     
     */
    public Paragraph getParagraph() {
        return paragraph;
    }

    /**
     * Sets the value of the paragraph property.
     * 
     * @param value
     *     allowed object is
     *     {@link Paragraph }
     *     
     */
    public void setParagraph(Paragraph value) {
        this.paragraph = value;
    }

    /**
     * Gets the value of the item property.
     * 
     * @return
     *     possible object is
     *     {@link Item }
     *     
     */
    public Item getItem() {
        return item;
    }

    /**
     * Sets the value of the item property.
     * 
     * @param value
     *     allowed object is
     *     {@link Item }
     *     
     */
    public void setItem(Item value) {
        this.item = value;
    }

    /**
     * Gets the value of the subItem property.
     * 
     * @return
     *     possible object is
     *     {@link SubItem }
     *     
     */
    public SubItem getSubItem() {
        return subItem;
    }

    /**
     * Sets the value of the subItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubItem }
     *     
     */
    public void setSubItem(SubItem value) {
        this.subItem = value;
    }

    /**
     * Gets the value of the ident property.
     * 
     * @return
     *     possible object is
     *     {@link Ident }
     *     
     */
    public Ident getIdent() {
        return ident;
    }

    /**
     * Sets the value of the ident property.
     * 
     * @param value
     *     allowed object is
     *     {@link Ident }
     *     
     */
    public void setIdent(Ident value) {
        this.ident = value;
    }

    /**
     * Gets the value of the placement property.
     * 
     * @return
     *     possible object is
     *     {@link PlacementType }
     *     
     */
    public PlacementType getPlacement() {
        return placement;
    }

    /**
     * Sets the value of the placement property.
     * 
     * @param value
     *     allowed object is
     *     {@link PlacementType }
     *     
     */
    public void setPlacement(PlacementType value) {
        this.placement = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link AmendmentType }
     *     
     */
    public AmendmentType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link AmendmentType }
     *     
     */
    public void setType(AmendmentType value) {
        this.type = value;
    }

}
